version: '3.8'

services:
  hubspot-agent:
    build: .
    ports:
      - "5012:5012"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///data/database.db
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRES=3600
      - HUBSPOT_API_URL=https://api.hubapi.com
      - HUBSPOT_ACCESS_TOKEN=your-hubspot-token-here
      - TWILIO_ACCOUNT_SID=your-twilio-account-sid
      - TWILIO_AUTH_TOKEN=your-twilio-auth-token
      - TWILIO_WHATSAPP_NUMBER=+14155238886
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5012/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
