version: '3.8'

services:
  hubspot-agent:
    build: .
    ports:
      - "5012:5012"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      DATABASE_URL: "sqlite:///:memory:"
      HUBSPOT_API_URL: https://api.hubapi.com
      HUBSPOT_ACCESS_TOKEN: ${HUBSPOT_ACCESS_TOKEN}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-secret-key}
      JWT_ACCESS_TOKEN_EXPIRES: 3600
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      TWILIO_WEBHOOK_URL: ${TWILIO_WEBHOOK_URL}
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      # Docker-specific settings
      DOCKER_ENV: "true"
      IGNORE_DATABASE_PERSISTENCE: "true"
      IGNORE_CACHE: "true"
      USE_IN_MEMORY_DB: "true"
      DISABLE_MIGRATIONS: "true"
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5012/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Simplified setup - no Redis or PostgreSQL needed
# Using in-memory SQLite database for Docker deployment
