version: '3.8'

services:
  hubspot-agent:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      DATABASE_URL: sqlite:///:memory:
      HUBSPOT_API_URL: https://api.hubapi.com
      # No system-level PAT - each user provides their own
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-secret-key}
      JWT_ACCESS_TOKEN_EXPIRES: 3600
      # Optional Twilio for WhatsApp
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      TWILIO_WEBHOOK_URL: ${TWILIO_WEBHOOK_URL}
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
